# Site settings
title: Alexis website
email: asagar@albany.edu
description: Alexis is a infomatics major from ny
url: http://asagar.github.io/
github_username: asagar

# Build settings
markdown: kramdown
permalink: pretty
